In [4]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
train= pd.read_csv('Train.csv')
test=pd.read_csv('test_l0Auv8Q.csv')
data = pd.read_excel("Data_Dictionary.xlsx")
fhc = pd.read_csv("First_Health_Camp_Attended.csv")
hc_detail = pd.read_csv("Health_Camp_Detail.csv")
pp = pd.read_csv("Patient_Profile.csv")
shc = pd.read_csv("Second_Health_Camp_Attended.csv")
thc = pd.read_csv("Third_Health_Camp_Attended.csv")

In [6]:
combined = pd.concat([train, test], ignore_index = True)

In [7]:
combined.shape

(110527, 8)

In [8]:
combined = pd.merge(left=combined, right=fhc, on=['Patient_ID','Health_Camp_ID'], how='left')
combined.shape

(110527, 11)

In [9]:
combined = pd.merge(left=combined, right=shc, on=['Patient_ID','Health_Camp_ID'], how='left')
combined.shape

(110527, 12)

In [10]:

combined = pd.merge(left=combined, right=thc, on=['Patient_ID','Health_Camp_ID'], how='left')
combined.shape

(110527, 14)

In [11]:
combined = pd.merge(left=combined, right=hc_detail, on='Health_Camp_ID', how='left')
combined.shape

(110527, 19)

In [12]:

combined = pd.merge(left=combined, right=pp, on='Patient_ID', how='left')
combined.shape

(110527, 29)

In [13]:
combined.isnull().sum()

Patient_ID                        0
Health_Camp_ID                    0
Registration_Date               334
Var1                              0
Var2                              0
Var3                              0
Var4                              0
Var5                              0
Donation                     104309
Health_Score                 104309
Unnamed: 4                   110527
Health Score                 102708
Number_of_stall_visited      104012
Last_Stall_Visited_Number    104012
Camp_Start_Date                   0
Camp_End_Date                     0
Category1                         0
Category2                         0
Category3                         0
Online_Follower                   0
LinkedIn_Shared                   0
Twitter_Shared                    0
Facebook_Shared                   0
Income                            0
Education_Score                   0
Age                               0
First_Interaction                 0
City_Type                     46602
Employer_Category             90963
dtype: int64

In [14]:
combined['Rgistraation_Date']=pd.to_datetime(combined.Registration_Date,dayfirst=True)

In [15]:
combined['Registration_Month']=combined.Rgistraation_Date.dt.month
combined['Registration_Day']=combined.Rgistraation_Date.dt.day
combined['Registration_year']=combined.Rgistraation_Date.dt.year

In [16]:
combined["Camp_End_Month"] = pd.DatetimeIndex(combined.Camp_End_Date).month
combined["Camp_End_Day"] = pd.DatetimeIndex(combined.Camp_End_Date).day
combined["Camp_End_Year"] = pd.DatetimeIndex(combined.Camp_End_Date).year

In [17]:
combined['Online_presence']=combined['Online_Follower']+combined['LinkedIn_Shared']+combined['Twitter_Shared']

In [18]:
combined.drop(['LinkedIn_Shared','Online_Follower','Twitter_Shared'],axis=1,inplace=True)

In [19]:
combined.shape

(110527, 34)

In [20]:
combined

,Patient_ID,Health_Camp_ID,Registration_Date,Var1,Var2,Var3,Var4,Var5,Donation,Health_Score,...,City_Type,Employer_Category,Rgistraation_Date,Registration_Month,Registration_Day,Registration_year,Camp_End_Month,Camp_End_Day,Camp_End_Year,Online_presence
0,489652,6578,10-Sep-05,4,0,0,0,2,NaN,NaN,...,NaN,NaN,2005-09-10,9.0,10.0,2005.0,10,14,2005,0
1,507246,6578,18-Aug-05,45,5,0,0,7,NaN,NaN,...,C,Others,2005-08-18,8.0,18.0,2005.0,10,14,2005,0
2,523729,6534,29-Apr-06,0,0,0,0,0,NaN,NaN,...,NaN,NaN,2006-04-29,4.0,29.0,2006.0,11,7,2007,0
3,524931,6535,07-Feb-04,0,0,0,0,0,NaN,NaN,...,I,NaN,2004-02-07,2.0,7.0,2004.0,2,18,2004,0
4,521364,6529,28-Feb-06,15,1,0,0,7,NaN,NaN,...,I,Technology,2006-02-28,2.0,28.0,2006.0,4,3,2006,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,507261,6525,13-Apr-06,12,2,0,0,6,NaN,NaN,...,NaN,NaN,2006-04-13,4.0,13.0,2006.0,4,17,2006,1
110523,513607,6551,03-Nov-06,0,0,0,0,0,NaN,NaN,...,G,NaN,2006-11-03,11.0,3.0,2006.0,11,18,2006,0
110524,498160,6584,17-Jun-06,0,0,0,0,0,NaN,NaN,...,A,NaN,2006-06-17,6.0,17.0,2006.0,8,9,2006,0
110525,502444,6567,13-Jan-07,0,0,0,0,0,NaN,NaN,...,NaN,NaN,2007-01-13,1.0,13.0,2007.0,2,4,2007,0
110526,523811,6584,16-Jun-06,4,3,0,2,4,NaN,NaN,...,D,Telecom,2006-06-16,6.0,16.0,2006.0,8,9,2006,0

In [21]:
combined["Camp_Start_Month"] = pd.DatetimeIndex(combined.Camp_Start_Date).month
combined["Camp_Start_Day"] = pd.DatetimeIndex(combined.Camp_Start_Date).day
combined["Camp_Start_Year"] = pd.DatetimeIndex(combined.Camp_Start_Date).year

In [22]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110527 entries, 0 to 110526
Data columns (total 37 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Patient_ID                 110527 non-null  int64
 1   Health_Camp_ID             110527 non-null  int64
 2   Registration_Date          110193 non-null  object
 3   Var1                       110527 non-null  int64
 4   Var2                       110527 non-null  int64
 5   Var3                       110527 non-null  int64
 6   Var4                       110527 non-null  int64
 7   Var5                       110527 non-null  int64
 8   Donation                   6218 non-null    float64
 9   Health_Score               6218 non-null    float64
 10  Unnamed: 4                 0 non-null       float64
 11  Health Score               7819 non-null    float64
 12  Number_of_stall_visited    6515 non-null    float64
 13  Last_Stall_Visited_Number  6515 non-null    float64
 14  Camp_Start_Date            110527 non-null  object
 15  Camp_End_Date              110527 non-null  object
 16  Category1                  110527 non-null  object
 17  Category2                  110527 non-null  object
 18  Category3                  110527 non-null  int64
 19  Facebook_Shared            110527 non-null  int64
 20  Income                     110527 non-null  object
 21  Education_Score            110527 non-null  object
 22  Age                        110527 non-null  object
 23  First_Interaction          110527 non-null  object
 24  City_Type                  63925 non-null   object
 25  Employer_Category          19564 non-null   object
 26  Rgistraation_Date          110193 non-null  datetime64[ns]
 27  Registration_Month         110193 non-null  float64
 28  Registration_Day           110193 non-null  float64
 29  Registration_year          110193 non-null  float64
 30  Camp_End_Month             110527 non-null  int64
 31  Camp_End_Day               110527 non-null  int64
 32  Camp_End_Year              110527 non-null  int64
 33  Online_presence            110527 non-null  int64
 34  Camp_Start_Month           110527 non-null  int64
 35  Camp_Start_Day             110527 non-null  int64
 36  Camp_Start_Year            110527 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(16), object(11)
memory usage: 32.0+ MB

In [23]:
combined.drop(['Registration_Date','Facebook_Shared'],axis=1,inplace=True)

In [24]:
combined['Camp_Start_Date']=pd.to_datetime(combined.Camp_Start_Date,dayfirst=True)
combined['Camp_End_Date']=pd.to_datetime(combined.Camp_End_Date,dayfirst=True)

In [25]:
combined['Camp_Duration']=(combined['Camp_End_Date']-combined['Camp_Start_Date']).dt.days

In [26]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110527 entries, 0 to 110526
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Patient_ID                 110527 non-null  int64
 1   Health_Camp_ID             110527 non-null  int64
 2   Var1                       110527 non-null  int64
 3   Var2                       110527 non-null  int64
 4   Var3                       110527 non-null  int64
 5   Var4                       110527 non-null  int64
 6   Var5                       110527 non-null  int64
 7   Donation                   6218 non-null    float64
 8   Health_Score               6218 non-null    float64
 9   Unnamed: 4                 0 non-null       float64
 10  Health Score               7819 non-null    float64
 11  Number_of_stall_visited    6515 non-null    float64
 12  Last_Stall_Visited_Number  6515 non-null    float64
 13  Camp_Start_Date            110527 non-null  datetime64[ns]
 14  Camp_End_Date              110527 non-null  datetime64[ns]
 15  Category1                  110527 non-null  object
 16  Category2                  110527 non-null  object
 17  Category3                  110527 non-null  int64
 18  Income                     110527 non-null  object
 19  Education_Score            110527 non-null  object
 20  Age                        110527 non-null  object
 21  First_Interaction          110527 non-null  object
 22  City_Type                  63925 non-null   object
 23  Employer_Category          19564 non-null   object
 24  Rgistraation_Date          110193 non-null  datetime64[ns]
 25  Registration_Month         110193 non-null  float64
 26  Registration_Day           110193 non-null  float64
 27  Registration_year          110193 non-null  float64
 28  Camp_End_Month             110527 non-null  int64
 29  Camp_End_Day               110527 non-null  int64
 30  Camp_End_Year              110527 non-null  int64
 31  Online_presence            110527 non-null  int64
 32  Camp_Start_Month           110527 non-null  int64
 33  Camp_Start_Day             110527 non-null  int64
 34  Camp_Start_Year            110527 non-null  int64
 35  Camp_Duration              110527 non-null  int64
dtypes: datetime64[ns](3), float64(9), int64(16), object(8)
memory usage: 31.2+ MB

In [27]:
combined['First_Interaction']=pd.to_datetime(combined.First_Interaction,dayfirst=True)
combined['Int_Days_diff']=(combined['Rgistraation_Date']-combined['First_Interaction']).dt.days

In [28]:
combined.head()

,Patient_ID,Health_Camp_ID,Var1,Var2,Var3,Var4,Var5,Donation,Health_Score,Unnamed: 4,...,Registration_year,Camp_End_Month,Camp_End_Day,Camp_End_Year,Online_presence,Camp_Start_Month,Camp_Start_Day,Camp_Start_Year,Camp_Duration,Int_Days_diff
0,489652,6578,4,0,0,0,2,NaN,NaN,NaN,...,2005.0,10,14,2005,0,8,16,2005,59,278.0
1,507246,6578,45,5,0,0,7,NaN,NaN,NaN,...,2005.0,10,14,2005,0,8,16,2005,59,344.0
2,523729,6534,0,0,0,0,0,NaN,NaN,NaN,...,2006.0,11,7,2007,0,10,17,2005,751,676.0
3,524931,6535,0,0,0,0,0,NaN,NaN,NaN,...,2004.0,2,18,2004,0,2,1,2004,17,0.0
4,521364,6529,15,1,0,0,7,NaN,NaN,NaN,...,2006.0,4,3,2006,0,3,30,2006,4,970.0

In [29]:
combined.Inc.vaomelue_counts()

AttributeError: 'DataFrame' object has no attribute 'Inc'

In [30]:
combined.groupby('Patient_ID')['Health_Camp_ID'].transform('nunique')

0         11
1         26
2          7
3          6
4         23
          ..
110522    26
110523     3
110524    16
110525     5
110526    14
Name: Health_Camp_ID, Length: 110527, dtype: int64

In [31]:
combined.groupby('Health_Camp_ID')['Patient_ID'].nunique()

Health_Camp_ID
6523    2084
6524     149
6525     166
6526    3809
6527    4144
        ...
6583    3026
6584    3041
6585    1398
6586    2624
6587      79
Name: Patient_ID, Length: 65, dtype: int64

In [32]:
combined['HC_per_patient']=combined.groupby('Patient_ID')['Health_Camp_ID'].transform('nunique')
combined['Patient_Per_HC']=combined.groupby('Health_Camp_ID')['Patient_ID'].transform('nunique')

In [33]:
combined.head(10)

,Patient_ID,Health_Camp_ID,Var1,Var2,Var3,Var4,Var5,Donation,Health_Score,Unnamed: 4,...,Camp_End_Day,Camp_End_Year,Online_presence,Camp_Start_Month,Camp_Start_Day,Camp_Start_Year,Camp_Duration,Int_Days_diff,HC_per_patient,Patient_Per_HC
0,489652,6578,4,0,0,0,2,NaN,NaN,NaN,...,14,2005,0,8,16,2005,59,278.0,11,2837
1,507246,6578,45,5,0,0,7,NaN,NaN,NaN,...,14,2005,0,8,16,2005,59,344.0,26,2837
2,523729,6534,0,0,0,0,0,NaN,NaN,NaN,...,7,2007,0,10,17,2005,751,676.0,7,3597
3,524931,6535,0,0,0,0,0,NaN,NaN,NaN,...,18,2004,0,2,1,2004,17,0.0,6,1882
4,521364,6529,15,1,0,0,7,NaN,NaN,NaN,...,3,2006,0,3,30,2006,4,970.0,23,3823
5,494493,6570,0,0,0,0,0,NaN,NaN,NaN,...,22,2005,0,7,9,2005,13,474.0,20,3564
6,523001,6562,0,0,0,0,0,NaN,NaN,NaN,...,2,2005,0,11,24,2004,190,45.0,3,2338
7,500733,6535,0,0,0,0,0,NaN,NaN,NaN,...,18,2004,0,2,1,2004,17,314.0,13,1882
8,501155,6538,0,0,0,0,0,NaN,NaN,NaN,...,4,2005,0,1,9,2004,392,0.0,2,3954
9,501457,6538,0,0,0,0,0,NaN,NaN,NaN,...,4,2005,0,1,9,2004,392,562.0,8,3954

In [34]:
#unique patients visited in thr beigning of camp year

combined['Patient_Per_Year']=combined.groupby('Camp_Start_Year')['Patient_ID'].transform('nunique')
combined['Patient_Per_Month']=combined.groupby('Camp_Start_Month')['Patient_ID'].transform('nunique')

In [35]:
combined['Patient_Per_End_Year']=combined.groupby('Camp_End_Year')['Patient_ID'].transform('nunique')
combined['Patient_Per_End_Month']=combined.groupby('Camp_End_Month')['Patient_ID'].transform('nunique')

In [36]:
combined.groupby('Camp_Start_Year')['Patient_ID'].nunique()

Camp_Start_Year
2003     3081
2004    10902
2005    22359
2006    16175
2007     2579
Name: Patient_ID, dtype: int64

In [37]:
combined.groupby('Camp_End_Year')['Patient_ID'].nunique()

Camp_End_Year
2003     1753
2004     6319
2005    17330
2006    14842
2007    14379
Name: Patient_ID, dtype: int64

In [38]:
combined.shape

(110527, 43)

In [39]:
combined.head()

,Patient_ID,Health_Camp_ID,Var1,Var2,Var3,Var4,Var5,Donation,Health_Score,Unnamed: 4,...,Camp_Start_Day,Camp_Start_Year,Camp_Duration,Int_Days_diff,HC_per_patient,Patient_Per_HC,Patient_Per_Year,Patient_Per_Month,Patient_Per_End_Year,Patient_Per_End_Month
0,489652,6578,4,0,0,0,2,NaN,NaN,NaN,...,16,2005,59,278.0,11,2837,22359,10445,17330,6109
1,507246,6578,45,5,0,0,7,NaN,NaN,NaN,...,16,2005,59,344.0,26,2837,22359,10445,17330,6109
2,523729,6534,0,0,0,0,0,NaN,NaN,NaN,...,17,2005,751,676.0,7,3597,22359,8242,14379,14643
3,524931,6535,0,0,0,0,0,NaN,NaN,NaN,...,1,2004,17,0.0,6,1882,10902,8717,6319,11010
4,521364,6529,15,1,0,0,7,NaN,NaN,NaN,...,30,2006,4,970.0,23,3823,16175,3823,14842,6519

In [40]:
combined.columns

Index(['Patient_ID', 'Health_Camp_ID', 'Var1', 'Var2', 'Var3', 'Var4', 'Var5',
       'Donation', 'Health_Score', 'Unnamed: 4', 'Health Score',
       'Number_of_stall_visited', 'Last_Stall_Visited_Number',
       'Camp_Start_Date', 'Camp_End_Date', 'Category1', 'Category2',
       'Category3', 'Income', 'Education_Score', 'Age', 'First_Interaction',
       'City_Type', 'Employer_Category', 'Rgistraation_Date',
       'Registration_Month', 'Registration_Day', 'Registration_year',
       'Camp_End_Month', 'Camp_End_Day', 'Camp_End_Year', 'Online_presence',
       'Camp_Start_Month', 'Camp_Start_Day', 'Camp_Start_Year',
       'Camp_Duration', 'Int_Days_diff', 'HC_per_patient', 'Patient_Per_HC',
       'Patient_Per_Year', 'Patient_Per_Month', 'Patient_Per_End_Year',
       'Patient_Per_End_Month'],
      dtype='object')

In [41]:
def outcome(a,b,c,d):
    if((a>0) | (b>0) | (c>0)):
        return(1)
    else:
        return(0)

In [42]:
combined['Target']=combined.apply(lambda x:outcome(x['Health_Score'],x['Health Score'],x['Number_of_stall_visited'],x['Last_Stall_Visited_Number']),axis=1)

In [43]:
drop=['Patient_ID', 'Health_Camp_ID','Donation', 'Health_Score', 'Unnamed: 4', 'Health Score','Education_Score', 'First_Interaction',
                  'City_Type', 'Employer_Category','Number_of_stall_visited', 'Last_Stall_Visited_Number','Age','Camp_Start_Date', 'Camp_End_Date','Rgistraation_Date']

In [44]:
len(drop)

16

In [45]:
## drop the unnecessary columns

new=combined.drop(['Patient_ID', 'Health_Camp_ID','Donation', 'Health_Score', 'Unnamed: 4', 'Health Score','Education_Score', 'First_Interaction',
                  'City_Type', 'Employer_Category','Number_of_stall_visited', 'Last_Stall_Visited_Number','Age','Camp_Start_Date', 'Camp_End_Date','Rgistraation_Date'],axis=1)

In [46]:
new.drop('Income',axis=1,inplace=True)

In [47]:
new.shape

(110527, 27)

In [48]:
new.head()

,Var1,Var2,Var3,Var4,Var5,Category1,Category2,Category3,Registration_Month,Registration_Day,...,Camp_Start_Year,Camp_Duration,Int_Days_diff,HC_per_patient,Patient_Per_HC,Patient_Per_Year,Patient_Per_Month,Patient_Per_End_Year,Patient_Per_End_Month,Target
0,4,0,0,0,2,Third,G,2,9.0,10.0,...,2005,59,278.0,11,2837,22359,10445,17330,6109,1
1,45,5,0,0,7,Third,G,2,8.0,18.0,...,2005,59,344.0,26,2837,22359,10445,17330,6109,0
2,0,0,0,0,0,Second,A,2,4.0,29.0,...,2005,751,676.0,7,3597,22359,8242,14379,14643,1
3,0,0,0,0,0,First,E,2,2.0,7.0,...,2004,17,0.0,6,1882,10902,8717,6319,11010,0
4,15,1,0,0,7,Second,A,2,2.0,28.0,...,2006,4,970.0,23,3823,16175,3823,14842,6519,1

In [49]:
mapped={'First':1,'Second':2,'Third':3}
new['Category1']=new.Category1.map(mapped)

In [50]:
#pd.factories does the same thing as label encoding
new['Category2']=pd.factorize(new.Category2,sort=True)[0]

In [51]:
new

,Var1,Var2,Var3,Var4,Var5,Category1,Category2,Category3,Registration_Month,Registration_Day,...,Camp_Start_Year,Camp_Duration,Int_Days_diff,HC_per_patient,Patient_Per_HC,Patient_Per_Year,Patient_Per_Month,Patient_Per_End_Year,Patient_Per_End_Month,Target
0,4,0,0,0,2,3,6,2,9.0,10.0,...,2005,59,278.0,11,2837,22359,10445,17330,6109,1
1,45,5,0,0,7,3,6,2,8.0,18.0,...,2005,59,344.0,26,2837,22359,10445,17330,6109,0
2,0,0,0,0,0,2,0,2,4.0,29.0,...,2005,751,676.0,7,3597,22359,8242,14379,14643,1
3,0,0,0,0,0,1,4,2,2.0,7.0,...,2004,17,0.0,6,1882,10902,8717,6319,11010,0
4,15,1,0,0,7,2,0,2,2.0,28.0,...,2006,4,970.0,23,3823,16175,3823,14842,6519,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,12,2,0,0,6,1,2,2,4.0,13.0,...,2006,9,786.0,26,166,16175,6164,14842,6519,0
110523,0,0,0,0,0,2,3,2,11.0,3.0,...,2006,5,415.0,3,2180,16175,8757,14842,14643,0
110524,0,0,0,0,0,2,0,2,6.0,17.0,...,2006,5,736.0,16,3041,16175,10445,14842,8663,0
110525,0,0,0,0,0,2,3,2,1.0,13.0,...,2007,5,619.0,5,2441,2579,9076,14379,11010,0
110526,4,3,0,2,4,2,0,2,6.0,16.0,...,2006,5,680.0,14,3041,16175,10445,14842,8663,0

In [52]:
new.isna().sum()

Var1                       0
Var2                       0
Var3                       0
Var4                       0
Var5                       0
Category1                  0
Category2                  0
Category3                  0
Registration_Month       334
Registration_Day         334
Registration_year        334
Camp_End_Month             0
Camp_End_Day               0
Camp_End_Year              0
Online_presence            0
Camp_Start_Month           0
Camp_Start_Day             0
Camp_Start_Year            0
Camp_Duration              0
Int_Days_diff            334
HC_per_patient             0
Patient_Per_HC             0
Patient_Per_Year           0
Patient_Per_Month          0
Patient_Per_End_Year       0
Patient_Per_End_Month      0
Target                     0
dtype: int64

In [53]:
for i in ['Registration_Month','Registration_Day','Registration_year']:
    new[i].fillna(new[i].mode()[0],inplace=True)

In [54]:
new['Int_Days_diff'].fillna(new['Int_Days_diff'].median(),inplace=True)

In [55]:
new.isna().sum()

Var1                     0
Var2                     0
Var3                     0
Var4                     0
Var5                     0
Category1                0
Category2                0
Category3                0
Registration_Month       0
Registration_Day         0
Registration_year        0
Camp_End_Month           0
Camp_End_Day             0
Camp_End_Year            0
Online_presence          0
Camp_Start_Month         0
Camp_Start_Day           0
Camp_Start_Year          0
Camp_Duration            0
Int_Days_diff            0
HC_per_patient           0
Patient_Per_HC           0
Patient_Per_Year         0
Patient_Per_Month        0
Patient_Per_End_Year     0
Patient_Per_End_Month    0
Target                   0
dtype: int64

In [56]:
from sklearn.model_selection import train_test_split                                  
###split the data train and test and delete the target

In [57]:

newtrain=new.loc[0:train.shape[0]-1,:]
newtest=new.loc[train.shape[0]:,:]

#drop the Target from test
newtest.drop('Target',axis=1,inplace=True)

In [58]:
newtrain.shape,newtest.shape

((75278, 27), (35249, 27))

In [59]:
## LOGISTIC REGRESSION

In [60]:
x=newtrain.drop('Target',axis=1)
y=newtrain.Target

In [61]:
pip install catboost

Requirement already satisfied: catboost in c:\programdata\anaconda3\lib\site-packages (1.0.6)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (from catboost) (3.4.3)
Requirement already satisfied: graphviz in c:\programdata\anaconda3\lib\site-packages (from catboost) (0.20.1)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.7.1)
Requirement already satisfied: plotly in c:\programdata\anaconda3\lib\site-packages (from catboost) (5.9.0)
Requirement already satisfied: numpy>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.20.3)
Requirement already satisfied: pandas>=0.24.0 in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.3.4)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.0->catboost) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from plotly->catboost) (8.0.1)

WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -5ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -4ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -3ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -2ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -1ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -0ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)

In [62]:
# pip install xgboost

In [90]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
import lightgbm as lgbm

In [64]:
lr=LogisticRegression()
rf=RandomForestClassifier()
gbm=GradientBoostingClassifier()


xgb=XGBClassifier(eval_metric='auc')
cboost=CatBoostClassifier(eval_metric='AUC')

In [69]:
x.head()

,Var1,Var2,Var3,Var4,Var5,Category1,Category2,Category3,Registration_Month,Registration_Day,...,Camp_Start_Day,Camp_Start_Year,Camp_Duration,Int_Days_diff,HC_per_patient,Patient_Per_HC,Patient_Per_Year,Patient_Per_Month,Patient_Per_End_Year,Patient_Per_End_Month
0,4,0,0,0,2,3,6,2,9.0,10.0,...,16,2005,59,278.0,11,2837,22359,10445,17330,6109
1,45,5,0,0,7,3,6,2,8.0,18.0,...,16,2005,59,344.0,26,2837,22359,10445,17330,6109
2,0,0,0,0,0,2,0,2,4.0,29.0,...,17,2005,751,676.0,7,3597,22359,8242,14379,14643
3,0,0,0,0,0,1,4,2,2.0,7.0,...,1,2004,17,0.0,6,1882,10902,8717,6319,11010
4,15,1,0,0,7,2,0,2,2.0,28.0,...,30,2006,4,970.0,23,3823,16175,3823,14842,6519

In [71]:
from sklearn.ensemble import VotingClassifier
vc=VotingClassifier(estimators=[('lr',lr),('rf',rf),('gbm',gbm),('xgb',xgb),('cboost',cboost)],voting='soft')

In [76]:
newtest.drop(columns="Target",axis=1, inplace=True)

In [77]:
pred=vc.fit(x,y).predict_proba(newtest)

Learning rate set to 0.065204
0:	total: 20.2ms	remaining: 20.2s
1:	total: 41.7ms	remaining: 20.8s
2:	total: 63.4ms	remaining: 21.1s
3:	total: 85.3ms	remaining: 21.2s
4:	total: 105ms	remaining: 20.9s
5:	total: 126ms	remaining: 20.9s
6:	total: 148ms	remaining: 21s
7:	total: 168ms	remaining: 20.9s
8:	total: 188ms	remaining: 20.7s
9:	total: 221ms	remaining: 21.9s
10:	total: 242ms	remaining: 21.8s
11:	total: 263ms	remaining: 21.6s
12:	total: 282ms	remaining: 21.4s
13:	total: 303ms	remaining: 21.3s
14:	total: 324ms	remaining: 21.3s
15:	total: 345ms	remaining: 21.2s
16:	total: 367ms	remaining: 21.2s
17:	total: 394ms	remaining: 21.5s
18:	total: 416ms	remaining: 21.5s
19:	total: 437ms	remaining: 21.4s
20:	total: 458ms	remaining: 21.4s
21:	total: 479ms	remaining: 21.3s
22:	total: 500ms	remaining: 21.2s
23:	total: 521ms	remaining: 21.2s
24:	total: 542ms	remaining: 21.1s
25:	total: 561ms	remaining: 21s
26:	total: 583ms	remaining: 21s
27:	total: 601ms	remaining: 20.9s
28:	total: 627ms	remaining: 21s
29:	total: 647ms	remaining: 20.9s
30:	total: 668ms	remaining: 20.9s
31:	total: 686ms	remaining: 20.8s
32:	total: 706ms	remaining: 20.7s
33:	total: 728ms	remaining: 20.7s
34:	total: 748ms	remaining: 20.6s
35:	total: 769ms	remaining: 20.6s
36:	total: 789ms	remaining: 20.5s
37:	total: 811ms	remaining: 20.5s
38:	total: 840ms	remaining: 20.7s
39:	total: 859ms	remaining: 20.6s
40:	total: 879ms	remaining: 20.6s
41:	total: 899ms	remaining: 20.5s
42:	total: 919ms	remaining: 20.5s
43:	total: 940ms	remaining: 20.4s
44:	total: 960ms	remaining: 20.4s
45:	total: 982ms	remaining: 20.4s
46:	total: 1s	remaining: 20.3s
47:	total: 1.02s	remaining: 20.3s
48:	total: 1.05s	remaining: 20.3s
49:	total: 1.07s	remaining: 20.4s
50:	total: 1.09s	remaining: 20.3s
51:	total: 1.11s	remaining: 20.3s
52:	total: 1.13s	remaining: 20.2s
53:	total: 1.15s	remaining: 20.2s
54:	total: 1.17s	remaining: 20.1s
55:	total: 1.19s	remaining: 20.1s
56:	total: 1.21s	remaining: 20s
57:	total: 1.23s	remaining: 20s
58:	total: 1.26s	remaining: 20.1s
59:	total: 1.28s	remaining: 20s
60:	total: 1.3s	remaining: 20s
61:	total: 1.32s	remaining: 20s
62:	total: 1.34s	remaining: 19.9s
63:	total: 1.36s	remaining: 19.9s
64:	total: 1.38s	remaining: 19.8s
65:	total: 1.4s	remaining: 19.8s
66:	total: 1.42s	remaining: 19.8s
67:	total: 1.44s	remaining: 19.7s
68:	total: 1.46s	remaining: 19.8s
69:	total: 1.48s	remaining: 19.7s
70:	total: 1.5s	remaining: 19.7s
71:	total: 1.53s	remaining: 19.7s
72:	total: 1.55s	remaining: 19.7s
73:	total: 1.57s	remaining: 19.6s
74:	total: 1.59s	remaining: 19.6s
75:	total: 1.61s	remaining: 19.5s
76:	total: 1.63s	remaining: 19.5s
77:	total: 1.64s	remaining: 19.4s
78:	total: 1.67s	remaining: 19.4s
79:	total: 1.69s	remaining: 19.4s
80:	total: 1.71s	remaining: 19.4s
81:	total: 1.73s	remaining: 19.4s
82:	total: 1.75s	remaining: 19.3s
83:	total: 1.77s	remaining: 19.3s
84:	total: 1.79s	remaining: 19.3s
85:	total: 1.81s	remaining: 19.2s
86:	total: 1.83s	remaining: 19.2s
87:	total: 1.85s	remaining: 19.2s
88:	total: 1.88s	remaining: 19.2s
89:	total: 1.9s	remaining: 19.2s
90:	total: 1.92s	remaining: 19.2s
91:	total: 1.94s	remaining: 19.2s
92:	total: 1.96s	remaining: 19.1s
93:	total: 1.98s	remaining: 19.1s
94:	total: 2.01s	remaining: 19.1s
95:	total: 2.03s	remaining: 19.1s
96:	total: 2.05s	remaining: 19.1s
97:	total: 2.07s	remaining: 19s
98:	total: 2.09s	remaining: 19.1s
99:	total: 2.11s	remaining: 19s
100:	total: 2.13s	remaining: 19s
101:	total: 2.15s	remaining: 19s
102:	total: 2.17s	remaining: 18.9s
103:	total: 2.19s	remaining: 18.9s
104:	total: 2.21s	remaining: 18.9s
105:	total: 2.24s	remaining: 18.9s
106:	total: 2.25s	remaining: 18.8s
107:	total: 2.27s	remaining: 18.8s
108:	total: 2.3s	remaining: 18.8s
109:	total: 2.32s	remaining: 18.8s
110:	total: 2.34s	remaining: 18.7s
111:	total: 2.36s	remaining: 18.7s
112:	total: 2.38s	remaining: 18.7s
113:	total: 2.4s	remaining: 18.7s
114:	total: 2.42s	remaining: 18.6s
115:	total: 2.44s	remaining: 18.6s
116:	total: 2.46s	remaining: 18.6s
117:	total: 2.48s	remaining: 18.5s
118:	total: 2.5s	remaining: 18.5s
119:	total: 2.52s	remaining: 18.5s
120:	total: 2.54s	remaining: 18.5s
121:	total: 2.56s	remaining: 18.4s
122:	total: 2.58s	remaining: 18.4s
123:	total: 2.6s	remaining: 18.4s
124:	total: 2.62s	remaining: 18.4s
125:	total: 2.64s	remaining: 18.3s
126:	total: 2.66s	remaining: 18.3s
127:	total: 2.68s	remaining: 18.3s
128:	total: 2.7s	remaining: 18.2s
129:	total: 2.73s	remaining: 18.2s
130:	total: 2.75s	remaining: 18.2s
131:	total: 2.77s	remaining: 18.2s
132:	total: 2.79s	remaining: 18.2s
133:	total: 2.8s	remaining: 18.1s
134:	total: 2.82s	remaining: 18.1s
135:	total: 2.84s	remaining: 18.1s
136:	total: 2.86s	remaining: 18s
137:	total: 2.88s	remaining: 18s
138:	total: 2.9s	remaining: 18s
139:	total: 2.92s	remaining: 18s
140:	total: 2.95s	remaining: 18s
141:	total: 2.97s	remaining: 18s
142:	total: 2.99s	remaining: 17.9s
143:	total: 3.01s	remaining: 17.9s
144:	total: 3.03s	remaining: 17.9s
145:	total: 3.06s	remaining: 17.9s
146:	total: 3.07s	remaining: 17.8s
147:	total: 3.1s	remaining: 17.8s
148:	total: 3.12s	remaining: 17.8s
149:	total: 3.14s	remaining: 17.8s
150:	total: 3.16s	remaining: 17.8s
151:	total: 3.18s	remaining: 17.8s
152:	total: 3.2s	remaining: 17.7s
153:	total: 3.22s	remaining: 17.7s
154:	total: 3.24s	remaining: 17.7s
155:	total: 3.27s	remaining: 17.7s
156:	total: 3.29s	remaining: 17.6s
157:	total: 3.31s	remaining: 17.6s
158:	total: 3.33s	remaining: 17.6s
159:	total: 3.35s	remaining: 17.6s
160:	total: 3.38s	remaining: 17.6s
161:	total: 3.4s	remaining: 17.6s
162:	total: 3.42s	remaining: 17.6s
163:	total: 3.44s	remaining: 17.5s
164:	total: 3.46s	remaining: 17.5s
165:	total: 3.48s	remaining: 17.5s
166:	total: 3.5s	remaining: 17.5s
167:	total: 3.52s	remaining: 17.5s
168:	total: 3.55s	remaining: 17.5s
169:	total: 3.57s	remaining: 17.4s
170:	total: 3.6s	remaining: 17.4s
171:	total: 3.62s	remaining: 17.4s
172:	total: 3.64s	remaining: 17.4s
173:	total: 3.66s	remaining: 17.4s
174:	total: 3.68s	remaining: 17.3s
175:	total: 3.7s	remaining: 17.3s
176:	total: 3.72s	remaining: 17.3s
177:	total: 3.74s	remaining: 17.3s
178:	total: 3.77s	remaining: 17.3s
179:	total: 3.8s	remaining: 17.3s
180:	total: 3.82s	remaining: 17.3s
181:	total: 3.85s	remaining: 17.3s
182:	total: 3.87s	remaining: 17.3s
183:	total: 3.89s	remaining: 17.3s
184:	total: 3.91s	remaining: 17.2s
185:	total: 3.94s	remaining: 17.2s
186:	total: 3.96s	remaining: 17.2s
187:	total: 3.99s	remaining: 17.2s
188:	total: 4.02s	remaining: 17.2s
189:	total: 4.04s	remaining: 17.2s
190:	total: 4.07s	remaining: 17.2s
191:	total: 4.09s	remaining: 17.2s
192:	total: 4.11s	remaining: 17.2s
193:	total: 4.14s	remaining: 17.2s
194:	total: 4.16s	remaining: 17.2s
195:	total: 4.19s	remaining: 17.2s
196:	total: 4.22s	remaining: 17.2s
197:	total: 4.25s	remaining: 17.2s
198:	total: 4.27s	remaining: 17.2s
199:	total: 4.29s	remaining: 17.2s
200:	total: 4.32s	remaining: 17.2s
201:	total: 4.34s	remaining: 17.2s
202:	total: 4.37s	remaining: 17.2s
203:	total: 4.4s	remaining: 17.2s
204:	total: 4.43s	remaining: 17.2s
205:	total: 4.45s	remaining: 17.2s
206:	total: 4.48s	remaining: 17.2s
207:	total: 4.51s	remaining: 17.2s
208:	total: 4.54s	remaining: 17.2s
209:	total: 4.57s	remaining: 17.2s
210:	total: 4.59s	remaining: 17.2s
211:	total: 4.61s	remaining: 17.2s
212:	total: 4.64s	remaining: 17.2s
213:	total: 4.67s	remaining: 17.2s
214:	total: 4.7s	remaining: 17.2s
215:	total: 4.72s	remaining: 17.2s
216:	total: 4.75s	remaining: 17.1s
217:	total: 4.77s	remaining: 17.1s
218:	total: 4.79s	remaining: 17.1s
219:	total: 4.82s	remaining: 17.1s
220:	total: 4.84s	remaining: 17.1s
221:	total: 4.86s	remaining: 17s
222:	total: 4.89s	remaining: 17s
223:	total: 4.91s	remaining: 17s
224:	total: 4.93s	remaining: 17s
225:	total: 4.95s	remaining: 17s
226:	total: 4.97s	remaining: 16.9s
227:	total: 5s	remaining: 16.9s
228:	total: 5.01s	remaining: 16.9s
229:	total: 5.03s	remaining: 16.9s
230:	total: 5.06s	remaining: 16.8s
231:	total: 5.09s	remaining: 16.8s
232:	total: 5.21s	remaining: 17.1s
233:	total: 5.25s	remaining: 17.2s
234:	total: 5.32s	remaining: 17.3s
235:	total: 5.35s	remaining: 17.3s
236:	total: 5.37s	remaining: 17.3s
237:	total: 5.39s	remaining: 17.3s
238:	total: 5.42s	remaining: 17.3s
239:	total: 5.45s	remaining: 17.2s
240:	total: 5.47s	remaining: 17.2s
241:	total: 5.49s	remaining: 17.2s
242:	total: 5.52s	remaining: 17.2s
243:	total: 5.54s	remaining: 17.2s
244:	total: 5.57s	remaining: 17.2s
245:	total: 5.59s	remaining: 17.1s
246:	total: 5.61s	remaining: 17.1s
247:	total: 5.64s	remaining: 17.1s
248:	total: 5.66s	remaining: 17.1s
249:	total: 5.68s	remaining: 17s
250:	total: 5.7s	remaining: 17s
251:	total: 5.72s	remaining: 17s
252:	total: 5.75s	remaining: 17s
253:	total: 5.78s	remaining: 17s
254:	total: 5.8s	remaining: 16.9s
255:	total: 5.82s	remaining: 16.9s
256:	total: 5.84s	remaining: 16.9s
257:	total: 5.86s	remaining: 16.9s
258:	total: 5.88s	remaining: 16.8s
259:	total: 5.9s	remaining: 16.8s
260:	total: 5.92s	remaining: 16.8s
261:	total: 5.94s	remaining: 16.7s
262:	total: 5.97s	remaining: 16.7s
263:	total: 5.99s	remaining: 16.7s
264:	total: 6.01s	remaining: 16.7s
265:	total: 6.03s	remaining: 16.6s
266:	total: 6.05s	remaining: 16.6s
267:	total: 6.07s	remaining: 16.6s
268:	total: 6.09s	remaining: 16.5s
269:	total: 6.11s	remaining: 16.5s
270:	total: 6.13s	remaining: 16.5s
271:	total: 6.14s	remaining: 16.4s
272:	total: 6.16s	remaining: 16.4s
273:	total: 6.19s	remaining: 16.4s
274:	total: 6.21s	remaining: 16.4s
275:	total: 6.24s	remaining: 16.4s
276:	total: 6.26s	remaining: 16.3s
277:	total: 6.28s	remaining: 16.3s
278:	total: 6.3s	remaining: 16.3s
279:	total: 6.33s	remaining: 16.3s
280:	total: 6.35s	remaining: 16.3s
281:	total: 6.37s	remaining: 16.2s
282:	total: 6.4s	remaining: 16.2s
283:	total: 6.43s	remaining: 16.2s
284:	total: 6.45s	remaining: 16.2s
285:	total: 6.47s	remaining: 16.1s
286:	total: 6.49s	remaining: 16.1s
287:	total: 6.5s	remaining: 16.1s
288:	total: 6.53s	remaining: 16.1s
289:	total: 6.54s	remaining: 16s
290:	total: 6.56s	remaining: 16s
291:	total: 6.58s	remaining: 16s
292:	total: 6.6s	remaining: 15.9s
293:	total: 6.63s	remaining: 15.9s
294:	total: 6.65s	remaining: 15.9s
295:	total: 6.67s	remaining: 15.9s
296:	total: 6.69s	remaining: 15.8s
297:	total: 6.71s	remaining: 15.8s
298:	total: 6.73s	remaining: 15.8s
299:	total: 6.75s	remaining: 15.7s
300:	total: 6.77s	remaining: 15.7s
301:	total: 6.79s	remaining: 15.7s
302:	total: 6.81s	remaining: 15.7s
303:	total: 6.83s	remaining: 15.6s
304:	total: 6.85s	remaining: 15.6s
305:	total: 6.87s	remaining: 15.6s
306:	total: 6.89s	remaining: 15.6s
307:	total: 6.91s	remaining: 15.5s
308:	total: 6.93s	remaining: 15.5s
309:	total: 6.95s	remaining: 15.5s
310:	total: 6.97s	remaining: 15.4s
311:	total: 6.99s	remaining: 15.4s
312:	total: 7s	remaining: 15.4s
313:	total: 7.03s	remaining: 15.3s
314:	total: 7.05s	remaining: 15.3s
315:	total: 7.07s	remaining: 15.3s
316:	total: 7.09s	remaining: 15.3s
317:	total: 7.11s	remaining: 15.3s
318:	total: 7.13s	remaining: 15.2s
319:	total: 7.15s	remaining: 15.2s
320:	total: 7.17s	remaining: 15.2s
321:	total: 7.19s	remaining: 15.1s
322:	total: 7.21s	remaining: 15.1s
323:	total: 7.23s	remaining: 15.1s
324:	total: 7.26s	remaining: 15.1s
325:	total: 7.28s	remaining: 15.1s
326:	total: 7.3s	remaining: 15s
327:	total: 7.32s	remaining: 15s
328:	total: 7.34s	remaining: 15s
329:	total: 7.36s	remaining: 14.9s
330:	total: 7.37s	remaining: 14.9s
331:	total: 7.39s	remaining: 14.9s
332:	total: 7.41s	remaining: 14.8s
333:	total: 7.43s	remaining: 14.8s
334:	total: 7.46s	remaining: 14.8s
335:	total: 7.48s	remaining: 14.8s
336:	total: 7.5s	remaining: 14.7s
337:	total: 7.52s	remaining: 14.7s
338:	total: 7.54s	remaining: 14.7s
339:	total: 7.56s	remaining: 14.7s
340:	total: 7.57s	remaining: 14.6s
341:	total: 7.59s	remaining: 14.6s
342:	total: 7.61s	remaining: 14.6s
343:	total: 7.63s	remaining: 14.6s
344:	total: 7.65s	remaining: 14.5s
345:	total: 7.68s	remaining: 14.5s
346:	total: 7.7s	remaining: 14.5s
347:	total: 7.71s	remaining: 14.5s
348:	total: 7.73s	remaining: 14.4s
349:	total: 7.75s	remaining: 14.4s
350:	total: 7.77s	remaining: 14.4s
351:	total: 7.79s	remaining: 14.3s
352:	total: 7.81s	remaining: 14.3s
353:	total: 7.83s	remaining: 14.3s
354:	total: 7.85s	remaining: 14.3s
355:	total: 7.87s	remaining: 14.2s
356:	total: 7.89s	remaining: 14.2s
357:	total: 7.91s	remaining: 14.2s
358:	total: 7.93s	remaining: 14.2s
359:	total: 7.95s	remaining: 14.1s
360:	total: 7.97s	remaining: 14.1s
361:	total: 7.99s	remaining: 14.1s
362:	total: 8.01s	remaining: 14.1s
363:	total: 8.03s	remaining: 14s
364:	total: 8.05s	remaining: 14s
365:	total: 8.07s	remaining: 14s
366:	total: 8.09s	remaining: 14s
367:	total: 8.12s	remaining: 13.9s
368:	total: 8.13s	remaining: 13.9s
369:	total: 8.16s	remaining: 13.9s
370:	total: 8.18s	remaining: 13.9s
371:	total: 8.19s	remaining: 13.8s
372:	total: 8.21s	remaining: 13.8s
373:	total: 8.23s	remaining: 13.8s
374:	total: 8.26s	remaining: 13.8s
375:	total: 8.28s	remaining: 13.7s
376:	total: 8.3s	remaining: 13.7s
377:	total: 8.32s	remaining: 13.7s
378:	total: 8.34s	remaining: 13.7s
379:	total: 8.36s	remaining: 13.6s
380:	total: 8.38s	remaining: 13.6s
381:	total: 8.4s	remaining: 13.6s
382:	total: 8.42s	remaining: 13.6s
383:	total: 8.44s	remaining: 13.5s
384:	total: 8.46s	remaining: 13.5s
385:	total: 8.49s	remaining: 13.5s
386:	total: 8.51s	remaining: 13.5s
387:	total: 8.53s	remaining: 13.4s
388:	total: 8.54s	remaining: 13.4s
389:	total: 8.56s	remaining: 13.4s
390:	total: 8.58s	remaining: 13.4s
391:	total: 8.6s	remaining: 13.3s
392:	total: 8.63s	remaining: 13.3s
393:	total: 8.65s	remaining: 13.3s
394:	total: 8.68s	remaining: 13.3s
395:	total: 8.7s	remaining: 13.3s
396:	total: 8.73s	remaining: 13.3s
397:	total: 8.75s	remaining: 13.2s
398:	total: 8.78s	remaining: 13.2s
399:	total: 8.8s	remaining: 13.2s
400:	total: 8.82s	remaining: 13.2s
401:	total: 8.85s	remaining: 13.2s
402:	total: 8.87s	remaining: 13.1s
403:	total: 8.9s	remaining: 13.1s
404:	total: 8.93s	remaining: 13.1s
405:	total: 8.95s	remaining: 13.1s
406:	total: 8.97s	remaining: 13.1s
407:	total: 9s	remaining: 13.1s
408:	total: 9.01s	remaining: 13s
409:	total: 9.03s	remaining: 13s
410:	total: 9.05s	remaining: 13s
411:	total: 9.07s	remaining: 13s
412:	total: 9.1s	remaining: 12.9s
413:	total: 9.12s	remaining: 12.9s
414:	total: 9.14s	remaining: 12.9s
415:	total: 9.16s	remaining: 12.9s
416:	total: 9.18s	remaining: 12.8s
417:	total: 9.2s	remaining: 12.8s
418:	total: 9.21s	remaining: 12.8s
419:	total: 9.24s	remaining: 12.8s
420:	total: 9.25s	remaining: 12.7s
421:	total: 9.27s	remaining: 12.7s
422:	total: 9.29s	remaining: 12.7s
423:	total: 9.32s	remaining: 12.7s
424:	total: 9.34s	remaining: 12.6s
425:	total: 9.36s	remaining: 12.6s
426:	total: 9.38s	remaining: 12.6s
427:	total: 9.4s	remaining: 12.6s
428:	total: 9.43s	remaining: 12.5s
429:	total: 9.44s	remaining: 12.5s
430:	total: 9.46s	remaining: 12.5s
431:	total: 9.5s	remaining: 12.5s
432:	total: 9.53s	remaining: 12.5s
433:	total: 9.57s	remaining: 12.5s
434:	total: 9.59s	remaining: 12.5s
435:	total: 9.61s	remaining: 12.4s
436:	total: 9.63s	remaining: 12.4s
437:	total: 9.66s	remaining: 12.4s
438:	total: 9.68s	remaining: 12.4s
439:	total: 9.71s	remaining: 12.4s
440:	total: 9.74s	remaining: 12.3s
441:	total: 9.78s	remaining: 12.3s
442:	total: 9.8s	remaining: 12.3s
443:	total: 9.84s	remaining: 12.3s
444:	total: 9.87s	remaining: 12.3s
445:	total: 9.89s	remaining: 12.3s
446:	total: 9.92s	remaining: 12.3s
447:	total: 9.95s	remaining: 12.3s
448:	total: 9.98s	remaining: 12.3s
449:	total: 10s	remaining: 12.2s
450:	total: 10s	remaining: 12.2s
451:	total: 10.1s	remaining: 12.2s
452:	total: 10.1s	remaining: 12.2s
453:	total: 10.1s	remaining: 12.2s
454:	total: 10.2s	remaining: 12.2s
455:	total: 10.2s	remaining: 12.2s
456:	total: 10.2s	remaining: 12.2s
457:	total: 10.3s	remaining: 12.1s
458:	total: 10.3s	remaining: 12.1s
459:	total: 10.3s	remaining: 12.1s
460:	total: 10.3s	remaining: 12.1s
461:	total: 10.4s	remaining: 12.1s
462:	total: 10.4s	remaining: 12s
463:	total: 10.4s	remaining: 12s
464:	total: 10.4s	remaining: 12s
465:	total: 10.5s	remaining: 12s
466:	total: 10.5s	remaining: 12s
467:	total: 10.5s	remaining: 11.9s
468:	total: 10.5s	remaining: 11.9s
469:	total: 10.6s	remaining: 11.9s
470:	total: 10.6s	remaining: 11.9s
471:	total: 10.6s	remaining: 11.9s
472:	total: 10.6s	remaining: 11.9s
473:	total: 10.7s	remaining: 11.8s
474:	total: 10.7s	remaining: 11.8s
475:	total: 10.7s	remaining: 11.8s
476:	total: 10.7s	remaining: 11.8s
477:	total: 10.8s	remaining: 11.7s
478:	total: 10.8s	remaining: 11.7s
479:	total: 10.8s	remaining: 11.7s
480:	total: 10.8s	remaining: 11.7s
481:	total: 10.9s	remaining: 11.7s
482:	total: 10.9s	remaining: 11.7s
483:	total: 10.9s	remaining: 11.6s
484:	total: 10.9s	remaining: 11.6s
485:	total: 11s	remaining: 11.6s
486:	total: 11s	remaining: 11.6s
487:	total: 11s	remaining: 11.5s
488:	total: 11s	remaining: 11.5s
489:	total: 11.1s	remaining: 11.5s
490:	total: 11.1s	remaining: 11.5s
491:	total: 11.1s	remaining: 11.5s
492:	total: 11.1s	remaining: 11.5s
493:	total: 11.2s	remaining: 11.4s
494:	total: 11.2s	remaining: 11.4s
495:	total: 11.2s	remaining: 11.4s
496:	total: 11.2s	remaining: 11.4s
497:	total: 11.2s	remaining: 11.3s
498:	total: 11.3s	remaining: 11.3s
499:	total: 11.3s	remaining: 11.3s
500:	total: 11.3s	remaining: 11.3s
501:	total: 11.3s	remaining: 11.3s
502:	total: 11.4s	remaining: 11.2s
503:	total: 11.4s	remaining: 11.2s
504:	total: 11.4s	remaining: 11.2s
505:	total: 11.5s	remaining: 11.2s
506:	total: 11.5s	remaining: 11.2s
507:	total: 11.5s	remaining: 11.2s
508:	total: 11.5s	remaining: 11.1s
509:	total: 11.6s	remaining: 11.1s
510:	total: 11.6s	remaining: 11.1s
511:	total: 11.6s	remaining: 11.1s
512:	total: 11.6s	remaining: 11s
513:	total: 11.6s	remaining: 11s
514:	total: 11.7s	remaining: 11s
515:	total: 11.7s	remaining: 10.9s
516:	total: 11.7s	remaining: 10.9s
517:	total: 11.7s	remaining: 10.9s
518:	total: 11.7s	remaining: 10.9s
519:	total: 11.8s	remaining: 10.9s
520:	total: 11.8s	remaining: 10.8s
521:	total: 11.8s	remaining: 10.8s
522:	total: 11.8s	remaining: 10.8s
523:	total: 11.8s	remaining: 10.7s
524:	total: 11.8s	remaining: 10.7s
525:	total: 11.9s	remaining: 10.7s
526:	total: 11.9s	remaining: 10.7s
527:	total: 11.9s	remaining: 10.7s
528:	total: 11.9s	remaining: 10.6s
529:	total: 12s	remaining: 10.6s
530:	total: 12s	remaining: 10.6s
531:	total: 12s	remaining: 10.6s
532:	total: 12s	remaining: 10.5s
533:	total: 12s	remaining: 10.5s
534:	total: 12.1s	remaining: 10.5s
535:	total: 12.1s	remaining: 10.5s
536:	total: 12.1s	remaining: 10.4s
537:	total: 12.1s	remaining: 10.4s
538:	total: 12.1s	remaining: 10.4s
539:	total: 12.2s	remaining: 10.4s
540:	total: 12.2s	remaining: 10.3s
541:	total: 12.2s	remaining: 10.3s
542:	total: 12.2s	remaining: 10.3s
543:	total: 12.2s	remaining: 10.3s
544:	total: 12.3s	remaining: 10.2s
545:	total: 12.3s	remaining: 10.2s
546:	total: 12.3s	remaining: 10.2s
547:	total: 12.3s	remaining: 10.2s
548:	total: 12.3s	remaining: 10.1s
549:	total: 12.4s	remaining: 10.1s
550:	total: 12.4s	remaining: 10.1s
551:	total: 12.4s	remaining: 10.1s
552:	total: 12.4s	remaining: 10s
553:	total: 12.4s	remaining: 10s
554:	total: 12.5s	remaining: 9.99s
555:	total: 12.5s	remaining: 9.96s
556:	total: 12.5s	remaining: 9.94s
557:	total: 12.5s	remaining: 9.91s
558:	total: 12.5s	remaining: 9.89s
559:	total: 12.6s	remaining: 9.86s
560:	total: 12.6s	remaining: 9.84s
561:	total: 12.6s	remaining: 9.81s
562:	total: 12.6s	remaining: 9.78s
563:	total: 12.6s	remaining: 9.76s
564:	total: 12.6s	remaining: 9.73s
565:	total: 12.7s	remaining: 9.7s
566:	total: 12.7s	remaining: 9.68s
567:	total: 12.7s	remaining: 9.66s
568:	total: 12.7s	remaining: 9.64s
569:	total: 12.7s	remaining: 9.61s
570:	total: 12.8s	remaining: 9.59s
571:	total: 12.8s	remaining: 9.56s
572:	total: 12.8s	remaining: 9.54s
573:	total: 12.8s	remaining: 9.51s
574:	total: 12.8s	remaining: 9.49s
575:	total: 12.9s	remaining: 9.46s
576:	total: 12.9s	remaining: 9.44s
577:	total: 12.9s	remaining: 9.42s

In [81]:
submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'Health_Camp_ID':test.Health_Camp_ID,
                       'Outcome':pred[:,1]})

In [82]:
submission.to_csv('Votingmodel1.csv', index=False)

In [83]:
submission.head()

   Patient_ID  Health_Camp_ID   Outcome
0      505701            6548  0.650620
1      500633            6584  0.391700
2      506945            6582  0.188253
3      497447            6551  0.529807
4      496446            6533  0.161407

In [93]:
## Cross validation for LGBM

In [94]:
from sklearn.model_selection import KFold 
import lightgbm as lgb
 
# Similarly LGBMRegressor can also be imported for a regression model.
from lightgbm import LGBMClassifier

In [97]:
kfold=KFold(n_splits=5, shuffle=True)

lgbm = LGBMClassifier(n_estimators=500, 
                     max_depth=10,
                     random_state=42,
                     learning_rate = 0.01,
                     scale_pos_weight =3)

pred_df = pd.DataFrame()
n=5
for i in range(n):
    folds = next(kfold.split(x)) ## next helps you iterate over next fold
    xtrain=x.iloc[folds[0]]  # builds x train data 
    ytrain=y.iloc[folds[0]] # creates y values 
    lgbm.fit(xtrain,ytrain)
    pred_df[i]=lgbm.predict_proba(newtest)[:,1]

In [98]:
median_prob=pred_df.median(axis=1)

In [100]:
submission2=pd.DataFrame({'Patient_ID':test.Patient_ID,'Health_Camp_ID':test.Health_Camp_ID,
                       'Outcome':median_prob})

In [101]:
submission2.to_csv('Votingmodel2.csv', index=False)

## Summary 

1. Model performance gets deastically impacted by the feature Engineering
2. we saw that LGBM appeared to be the best model across for this competition leading at #2 in the Public Leaderboard.
3. We saw that Features selected using RFECV did not work well and we had to discard that model.
4. Parameter tuning of LGB< can take the modelperformance at a whole another level. 
5. Cross Validation MOdel for LGB< did a fantastic job earning us a coup;e of brownie points on Public Leaderboard.
6. We learnt that the Target variable can be masked in the dataset which can be extracted by studying the problem statemen meticulously